### ISSUE TITLE
Error on instantiate categorizable model

### ISSUE THREAD

**Issue by NassarX** [rinvex/obsolete-category#20]
Hey, 
First, Thank you for your efforts to this package,,
 
Tut there are error when trying to create an entity as i get:

`Declaration of Rinvex\Category\Categorizable::created($callback, $priority = 0) must be compatible with Illuminate\Database\Eloquent\Model::created($callback)`

According to [Remove priority commite](https://github.com/illuminate/database/commit/0788db1856d7ae24ed560f8c838d731e1f24630e) observable events need to be updated.

**Comment by Omranic** [comment]
@NassarX Sorry, I missed this issue. But anyway should be fixed in the latest tagged release **v2.0.0** 👍  Fee free to open a new issue if you need any assistance..

**Comment by NassarX** [comment]
Thanks @Omranic but I can't switch to  **dev-develop** version as I get `rinvex/category v2.0.0  requires rinvex/cacheable dev-develop ` error on composer update .

**Comment by Omranic** [comment]
You may have to change your project's package minimum stability to **dev** so you can require untagged packages. Please feel free to followup about this issue on the newly rebranded package here https://github.com/rinvex/categorizable
